name: Make Electron App
on:
  push:

permissions: {}
jobs:
  make:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Build and make
        run: |
          pnpm install
          pnpm make
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: app zip
          path: |
            out/make/zip
          retention-days: 10
          if-no-files-found: ignore
